name: build
on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Set up Go 1.12
      uses: cedrickring/golang-action/go1.12@1.3.0
      env:
        GO111MODULE: "on"

    - name: Get dependencies
      run: go mod vendor

    - name: Build
      run: go build -v
      
    - name: Test
      run: go test -v
